import { Playfair_Display } from 'next/font/google';
import './globals.css';
import GradientBackground from './GradientBackground'; // Import the gradient background

const playfair = Playfair_Display({
    subsets: ["latin"],
    weight: ['400', '700'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playfair.className}>
        
        
        {children}
      </body>
    </html>
  );
}